name: Create Release

on: 
  push:
    branches:
      - release_*
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get Version Number
      id: version_number
      uses: frabert/replace-string-action@v1.1
      with:
        string: ${{ github.ref }}
        pattern: 'ref/heads/release_'
        replace-with: ''
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_number.outputs.replaced }}
        release_name: ${{ steps.version_number.outputs.replaced }}
        draft: true
        prerelease: if (contains(steps.version_number_outputs.replaced, 'alpha') || contains(steps.version_number_outputs.replaced, 'beta'))
